apiVersion: v1
kind: PersistentVolume
metadata:
  name: newsletter-pv
  labels:
    app: newsletter
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
